/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Org
         * @description Own org in full; any other org: name, type and location only.
         */
        get: operations["get_org_api_v1_orgs__org_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Facilities
         * @description Own org's facilities in full; another org's: name and location only.
         */
        get: operations["list_facilities_api_v1_orgs__org_id__facilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit
         * @description Own org's rows, newest first; the platform admin sees every org's rows.
         */
        get: operations["list_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Products
         * @description The shared catalog; any signed-in user.
         */
        get: operations["list_products_api_v1_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_v1_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/supplier-offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Offers
         * @description The caller's own org's offers only.
         */
        get: operations["list_offers_api_v1_supplier_offers_get"];
        /**
         * Put Offer
         * @description Create or update one offer of the caller's supplier org (SUPPLIER orgs only). Then
         *     re-runs other orgs' "No eligible source" shortages for the product (§5).
         */
        put: operations["put_offer_api_v1_supplier_offers_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Batches
         * @description The caller's own org's batches, each with the hub-computed `transferable`.
         */
        get: operations["list_batches_api_v1_inventory_batches_get"];
        put?: never;
        /** Create Batch */
        post: operations["create_batch_api_v1_inventory_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/batches/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Batches
         * @description Insert each valid row into `facility_id`; report invalid rows by line number.
         */
        post: operations["import_batches_api_v1_inventory_batches_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Batch */
        patch: operations["update_batch_api_v1_inventory_batches__batch_id__patch"];
        trace?: never;
    };
    "/api/v1/inventory/batches/{batch_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Batch
         * @description Record a physical count: writes a VerificationEvent, sets last_verified_at, and a
         *     count that differs from on_hand replaces it.
         */
        post: operations["verify_batch_api_v1_inventory_batches__batch_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Shortages
         * @description The caller's own org's shortages, newest first.
         */
        get: operations["list_shortages_api_v1_shortages_get"];
        put?: never;
        /**
         * Create Shortage
         * @description Create a shortage in the caller's org. The hub computes the shortfall and runs the
         *     first match, so the shortage comes back MATCHING.
         */
        post: operations["create_shortage_api_v1_shortages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortages/{shortage_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shortage */
        get: operations["get_shortage_api_v1_shortages__shortage_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortages/{shortage_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Shortage
         * @description Allowed from OPEN, MATCHING or AWAITING_DECISION; otherwise 409 `invalid_transition`.
         */
        post: operations["cancel_shortage_api_v1_shortages__shortage_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortages/{shortage_id}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rerun Match
         * @description Manual re-run while the shortage is OPEN or MATCHING; otherwise 409.
         */
        post: operations["rerun_match_api_v1_shortages__shortage_id__match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortages/{shortage_id}/match-runs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest Match Run
         * @description Any user of the requester's org: eligible candidates by rank, then rejected ones with
         *     every failed gate's reason.
         */
        get: operations["latest_match_run_api_v1_shortages__shortage_id__match_runs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/internal/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Telemetry
         * @description For services/iot-ingest only (ingest token, scope `telemetry.write`). Idempotent:
         *     a reading whose (device_id, ts) is already stored counts as a duplicate.
         */
        post: operations["post_telemetry_api_v1_internal_telemetry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Devices
         * @description The caller's own org's devices, with last_seen and battery.
         */
        get: operations["list_devices_api_v1_devices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Source Requests
         * @description `incoming`: requests the caller's org is asked to supply. `outgoing`: requests sent
         *     for the caller's org's shortages. Newest first; optional `status` and `shortage_id`.
         */
        get: operations["list_source_requests_api_v1_source_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-requests/{request_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Source Request
         * @description Source org only. Places TENTATIVE holds on the source's batches (earliest expiry
         *     first) and moves the request to TENTATIVE_HOLD. 409 `conflict` if the stock no longer
         *     covers it: the request is then EXPIRED ("Stock changed before acceptance.") and matching
         *     re-runs. 409 `invalid_transition` if it is not REQUESTED, or its deadline has passed.
         */
        post: operations["accept_source_request_api_v1_source_requests__request_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/source-requests/{request_id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decline Source Request
         * @description Source org only; the reason is optional. Matching re-runs without this org for the
         *     shortage. 409 `invalid_transition` if it is not REQUESTED, or its deadline has passed.
         */
        post: operations["decline_source_request_api_v1_source_requests__request_id__decline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Stream Ticket
         * @description A 60-second ticket that opens GET /events/stream as the caller (`?ticket=`), because
         *     a browser EventSource cannot send an Authorization header.
         */
        post: operations["create_stream_ticket_api_v1_events_ticket_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Event Stream
         * @description Server-sent events for the caller's org: only events whose `org_ids` include it.
         *
         *     Each message is `id: <seq>` and `data: <envelope>`, where the envelope is
         *     `{id, type, occurred_at, org_ids, data}` (api-and-events.md, Events). A comment line
         *     (`: heartbeat`) is sent after 15 seconds without events. Reconnect with the last `id` as the
         *     `Last-Event-ID` header or `last_event_id` query parameter to replay what was missed; if too
         *     much was missed, the stream sends `event: reset` instead, and the client should refetch.
         *     The stream closes after 15 minutes; reconnect with a new ticket.
         */
        get: operations["event_stream_api_v1_events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Webhooks
         * @description The caller's org's subscriptions, oldest first. Secrets are never listed.
         */
        get: operations["list_webhooks_api_v1_webhooks_get"];
        put?: never;
        /**
         * Create Webhook
         * @description Subscribe the caller's org: events of `event_types` addressed to it are POSTed to
         *     `url`, signed in `X-CareE-Signature`. The secret is in this response only.
         */
        post: operations["create_webhook_api_v1_webhooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/{webhook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Webhook
         * @description Own org's subscription only (403 otherwise). Its pending deliveries stop.
         */
        delete: operations["delete_webhook_api_v1_webhooks__webhook_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditOut */
        AuditOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Actor Id */
            actor_id: string | null;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Entity */
            entity: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Action */
            action: string;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
            /** Reason */
            reason: string;
            /** Reason Source */
            reason_source: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** BatchCreate */
        BatchCreate: {
            /** Batch No */
            batch_no: string;
            /** On Hand */
            on_hand: number;
            /**
             * Reserved
             * @default 0
             */
            reserved: number;
            /**
             * Allocated
             * @default 0
             */
            allocated: number;
            /**
             * Safety Stock
             * @default 0
             */
            safety_stock: number;
            /**
             * Quarantined
             * @default 0
             */
            quarantined: number;
            /**
             * Expiry Date
             * Format: date
             */
            expiry_date: string;
            /** Unit Cost Paise */
            unit_cost_paise: number;
            /**
             * Facility Id
             * Format: uuid
             */
            facility_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Reason */
            reason?: string | null;
        };
        /** BatchOut */
        BatchOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * Facility Id
             * Format: uuid
             */
            facility_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Batch No */
            batch_no: string;
            /** On Hand */
            on_hand: number;
            /** Reserved */
            reserved: number;
            /** Allocated */
            allocated: number;
            /** Safety Stock */
            safety_stock: number;
            /** Quarantined */
            quarantined: number;
            /**
             * Expiry Date
             * Format: date
             */
            expiry_date: string;
            /** Unit Cost Paise */
            unit_cost_paise: number;
            /** Last Verified At */
            last_verified_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Transferable
             * @description Hub-computed (business-rules.md §2); never accepted as input.
             */
            readonly transferable: number;
            /**
             * Held Qty
             * @description Units under active source-request holds; counted as reserved.
             */
            readonly held_qty: number;
        };
        /**
         * BatchUpdate
         * @description Partial update. Product and facility are fixed; omitted or null fields are unchanged.
         */
        BatchUpdate: {
            /** Batch No */
            batch_no?: string | null;
            /** On Hand */
            on_hand?: number | null;
            /** Reserved */
            reserved?: number | null;
            /** Allocated */
            allocated?: number | null;
            /** Safety Stock */
            safety_stock?: number | null;
            /** Quarantined */
            quarantined?: number | null;
            /** Expiry Date */
            expiry_date?: string | null;
            /** Unit Cost Paise */
            unit_cost_paise?: number | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * CandidateOut
         * @description What the requester's org sees of a source: no batch ids, raw stock figures or, for a
         *     hospital source, cost (it would reveal that hospital's unit cost; CLAUDE.md rule 6).
         */
        CandidateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Source Org Id
             * Format: uuid
             */
            source_org_id: string;
            /** Source Org Name */
            source_org_name: string;
            source_type: components["schemas"]["SourceType"];
            /**
             * Transferable Qty
             * @description Hospital sources: hub-computed.
             */
            transferable_qty: number | null;
            /**
             * Offered Qty
             * @description Supplier sources: the offer's available qty.
             */
            offered_qty: number | null;
            /** Gate Results */
            gate_results: components["schemas"]["GateOut"][];
            /** Eligible */
            eligible: boolean;
            /**
             * Landed Cost Paise
             * @description Eligible supplier candidates only; never shown for a hospital source.
             */
            landed_cost_paise: number | null;
            /** Eta Hours */
            eta_hours: number;
            /** Reliability */
            reliability: number;
            /**
             * Rank
             * @description 1 = best; eligible candidates only.
             */
            rank: number | null;
        };
        /** DeviceOut */
        DeviceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Device Id */
            device_id: string;
            /** Type */
            type: string;
            /** Battery Level */
            battery_level: number | null;
            /** Last Seen */
            last_seen: string | null;
        };
        /**
         * Direction
         * @enum {string}
         */
        Direction: "incoming" | "outgoing";
        /**
         * EventType
         * @enum {string}
         */
        EventType: "shortage.status_changed" | "source_request.created" | "source_request.status_changed" | "recommendation.ready" | "purchase_order.created" | "purchase_order.status_changed" | "shipment.created" | "shipment.status_changed" | "shipment.location" | "coldchain.reading" | "coldchain.excursion" | "coldchain.device_silent" | "coldchain.recovered" | "reconciliation.completed" | "surplus.matched" | "inventory.changed" | "supplier_offer.changed";
        /** FacilityOut */
        FacilityOut: {
            /** Name */
            name: string;
            location: components["schemas"]["Location"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Address */
            address: string;
            /** Has Cold Storage */
            has_cold_storage: boolean;
        };
        /** GateOut */
        GateOut: {
            /** Gate */
            gate: string;
            /** Passed */
            passed: boolean;
            /** Reason */
            reason: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoldOut */
        HoldOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Qty */
            qty: number;
            status: components["schemas"]["HoldStatus"];
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * HoldStatus
         * @enum {string}
         */
        HoldStatus: "TENTATIVE" | "FIRM" | "RELEASED";
        /** ImportResult */
        ImportResult: {
            /** Inserted */
            inserted: number;
            /** Errors */
            errors: components["schemas"]["RowError"][];
        };
        /** Location */
        Location: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MatchRunOut */
        MatchRunOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Shortage Id
             * Format: uuid
             */
            shortage_id: string;
            /** Run No */
            run_no: number;
            triggered_by: components["schemas"]["Trigger"];
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Excluded Org Ids */
            excluded_org_ids: string[];
            planned_resolution: components["schemas"]["PlannedResolution"] | null;
            /**
             * Reason
             * @description "No eligible source" when nothing is eligible.
             */
            reason: string | null;
            /**
             * Candidates
             * @description Eligible by rank, then rejected.
             */
            candidates: components["schemas"]["CandidateOut"][];
        };
        /** MeOut */
        MeOut: {
            user: components["schemas"]["UserOut"];
            org: components["schemas"]["OrgOut"];
            /** Roles */
            roles: string[];
            /** Capabilities */
            capabilities: string[];
        };
        /**
         * OfferIn
         * @description One offer per PUT, keyed by the caller's org and `product_id` (upsert).
         */
        OfferIn: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Unit Price Paise */
            unit_price_paise: number;
            /** Lead Time Hours */
            lead_time_hours: number;
            /** Available Qty */
            available_qty: number;
            /** Reason */
            reason?: string | null;
        };
        /** OfferOut */
        OfferOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Unit Price Paise */
            unit_price_paise: number;
            /** Lead Time Hours */
            lead_time_hours: number;
            /** Available Qty */
            available_qty: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OrgOut */
        OrgOut: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            location: components["schemas"]["Location"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
        };
        /** Page[AuditOut] */
        Page_AuditOut_: {
            /** Items */
            items: components["schemas"]["AuditOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[BatchOut] */
        Page_BatchOut_: {
            /** Items */
            items: components["schemas"]["BatchOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[DeviceOut] */
        Page_DeviceOut_: {
            /** Items */
            items: components["schemas"]["DeviceOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[FacilityOut] */
        Page_FacilityOut_: {
            /** Items */
            items: components["schemas"]["FacilityOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[OfferOut] */
        Page_OfferOut_: {
            /** Items */
            items: components["schemas"]["OfferOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[ProductOut] */
        Page_ProductOut_: {
            /** Items */
            items: components["schemas"]["ProductOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[PublicFacilityView] */
        Page_PublicFacilityView_: {
            /** Items */
            items: components["schemas"]["PublicFacilityView"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[ShortageOut] */
        Page_ShortageOut_: {
            /** Items */
            items: components["schemas"]["ShortageOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[SourceRequestOut] */
        Page_SourceRequestOut_: {
            /** Items */
            items: components["schemas"]["SourceRequestOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[WebhookOut] */
        Page_WebhookOut_: {
            /** Items */
            items: components["schemas"]["WebhookOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** PlanLine */
        PlanLine: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /**
             * Source Org Id
             * Format: uuid
             */
            source_org_id: string;
            source_type: components["schemas"]["SourceType"];
            /** Qty */
            qty: number;
            /**
             * Landed Cost Paise
             * @description Supplier lines only, as for candidates.
             */
            landed_cost_paise: number | null;
            /** Eta Hours */
            eta_hours: number;
        };
        /** PlannedResolution */
        PlannedResolution: {
            /**
             * Type
             * @enum {string}
             */
            type: "TRANSFER" | "TRANSFER_SPLIT" | "BUY";
            /** Lines */
            lines: components["schemas"]["PlanLine"][];
            /**
             * Alternatives
             * @description The best BUY, or for a BUY the next one.
             */
            alternatives: components["schemas"]["PlanLine"][];
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "CRITICAL" | "ROUTINE";
        /** ProductOut */
        ProductOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Unit */
            unit: string;
            /** Requires Cold Chain */
            requires_cold_chain: boolean;
            /** Temp Min C */
            temp_min_c: number | null;
            /** Temp Max C */
            temp_max_c: number | null;
            /** Default Min Shelf Life Days */
            default_min_shelf_life_days: number;
        };
        /** PublicFacilityView */
        PublicFacilityView: {
            /** Name */
            name: string;
            location: components["schemas"]["Location"];
        };
        /**
         * PublicOrgView
         * @description What any org may see of another org: name, type, location only.
         */
        PublicOrgView: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            location: components["schemas"]["Location"];
        };
        /**
         * ReadingIn
         * @description One reading as the cold box publishes it (apps-ai-iot.md, Firmware).
         */
        ReadingIn: {
            /** Device Id */
            device_id: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Temp C */
            temp_c: number;
            /** Battery */
            battery?: number | null;
        };
        /** ReasonIn */
        ReasonIn: {
            /** Reason */
            reason?: string | null;
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RequestStatus
         * @enum {string}
         */
        RequestStatus: "REQUESTED" | "TENTATIVE_HOLD" | "DECLINED" | "EXPIRED" | "SUPERSEDED" | "CONFIRMED";
        /** RowError */
        RowError: {
            /** Line */
            line: number;
            /** Message */
            message: string;
        };
        /**
         * ShortageCreate
         * @description Any unknown field is a 422, except `shortfall`: the hub computes it
         *     (business-rules.md §1), so a client value is accepted and ignored.
         */
        ShortageCreate: {
            /**
             * Facility Id
             * Format: uuid
             */
            facility_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Qty Required */
            qty_required: number;
            /** Qty Local Usable */
            qty_local_usable: number;
            /**
             * Required By
             * Format: date-time
             */
            required_by: string;
            priority: components["schemas"]["Priority"];
            /**
             * Min Shelf Life Days
             * @description Defaults to the product's default_min_shelf_life_days.
             */
            min_shelf_life_days?: number | null;
            /** Notes */
            notes?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** ShortageOut */
        ShortageOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * Facility Id
             * Format: uuid
             */
            facility_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Qty Required */
            qty_required: number;
            /** Qty Local Usable */
            qty_local_usable: number;
            /**
             * Shortfall
             * @description Hub-computed max(0, qty_required - qty_local_usable); never taken as input.
             */
            readonly shortfall: number;
            /**
             * Required By
             * Format: date-time
             */
            required_by: string;
            priority: components["schemas"]["Priority"];
            /** Min Shelf Life Days */
            min_shelf_life_days: number;
            status: components["schemas"]["Status"];
            /** Notes */
            notes: string | null;
            /** Parent Shortage Id */
            parent_shortage_id: string | null;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
            source: components["schemas"]["ShortageSource"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ShortageSource
         * @enum {string}
         */
        ShortageSource: "FORM" | "CHAT";
        /**
         * SourceRequestOut
         * @description Both orgs see the request itself. Only the source org sees which of its batches are
         *     held (`holds`); the requester sees the total (`held_qty`) and the hold deadline.
         */
        SourceRequestOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Shortage Id
             * Format: uuid
             */
            shortage_id: string;
            /**
             * Requester Org Id
             * Format: uuid
             */
            requester_org_id: string;
            /** Requester Org Name */
            requester_org_name: string;
            /**
             * Source Org Id
             * Format: uuid
             */
            source_org_id: string;
            /** Source Org Name */
            source_org_name: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            priority: components["schemas"]["Priority"];
            /**
             * Required By
             * Format: date-time
             */
            required_by: string;
            /** Qty */
            qty: number;
            status: components["schemas"]["RequestStatus"];
            /**
             * Sla Deadline
             * Format: date-time
             * @description When the source must accept or decline.
             */
            sla_deadline: string;
            /**
             * Hold Expires At
             * @description When the tentative holds lapse unless the requester decides.
             */
            hold_expires_at: string | null;
            /**
             * Held Qty
             * @description Units under active (TENTATIVE or FIRM) holds.
             */
            held_qty: number;
            /**
             * Holds
             * @description Source org only; null for the requester.
             */
            holds: components["schemas"]["HoldOut"][] | null;
            /** Responded By */
            responded_by: string | null;
            /** Responded At */
            responded_at: string | null;
            /** Decline Reason */
            decline_reason: string | null;
            /**
             * Reason Source
             * @description On a decline: USER if the source typed a reason, else SYSTEM.
             */
            reason_source: ("USER" | "SYSTEM") | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "HOSPITAL" | "SUPPLIER";
        /**
         * Status
         * @enum {string}
         */
        Status: "DRAFT" | "OPEN" | "MATCHING" | "AWAITING_DECISION" | "IN_FULFILLMENT" | "RECEIVED" | "RESOLVED" | "PARTIALLY_RESOLVED" | "CANCELLED";
        /** StreamTicketOut */
        StreamTicketOut: {
            /**
             * Ticket
             * @description Pass as `?ticket=` to GET /events/stream (EventSource cannot send headers).
             */
            ticket: string;
            /**
             * Expires At
             * Format: date-time
             * @description Open the stream before this; it lasts 60 seconds.
             */
            expires_at: string;
        };
        /** TelemetryBatch */
        TelemetryBatch: {
            /** Readings */
            readings: components["schemas"]["ReadingIn"][];
        };
        /** TelemetryResult */
        TelemetryResult: {
            /**
             * Stored
             * @description New readings saved.
             */
            stored: number;
            /**
             * Duplicates
             * @description Readings already stored (same device_id and ts).
             */
            duplicates: number;
            /**
             * Unknown Devices
             * @description device_ids with no Device; not stored.
             */
            unknown_devices: string[];
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /**
         * Trigger
         * @enum {string}
         */
        Trigger: "CREATE" | "DECLINE" | "EXPIRY" | "MANUAL" | "RECOMMENDATION_EXPIRED" | "STOCK_CHANGE";
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerificationMethod
         * @enum {string}
         */
        VerificationMethod: "MANUAL" | "SCAN";
        /**
         * VerifyIn
         * @description `method` is required: the hub records only the count method the user stated.
         */
        VerifyIn: {
            method: components["schemas"]["VerificationMethod"];
            /** Counted Qty */
            counted_qty: number;
            /** Reason */
            reason?: string | null;
        };
        /** WebhookCreated */
        WebhookCreated: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Url */
            url: string;
            /** Event Types */
            event_types: components["schemas"]["EventType"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Secret
             * @description Shown only now. Verify `X-CareE-Signature: sha256=<hex HMAC-SHA256 of the raw body>` with it.
             */
            secret: string;
        };
        /** WebhookIn */
        WebhookIn: {
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Event Types */
            event_types: components["schemas"]["EventType"][];
            /** Reason */
            reason?: string | null;
        };
        /** WebhookOut */
        WebhookOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Url */
            url: string;
            /** Event Types */
            event_types: components["schemas"]["EventType"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    get_org_api_v1_orgs__org_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgOut"] | components["schemas"]["PublicOrgView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_facilities_api_v1_orgs__org_id__facilities_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FacilityOut_"] | components["schemas"]["Page_PublicFacilityView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_v1_audit_get: {
        parameters: {
            query?: {
                entity?: string | null;
                entity_id?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_v1_products_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProductOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_v1_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_offers_api_v1_supplier_offers_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OfferOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_offer_api_v1_supplier_offers_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_api_v1_inventory_batches_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BatchOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_batch_api_v1_inventory_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_batches_api_v1_inventory_batches_import_post: {
        parameters: {
            query: {
                facility_id: string;
                reason?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description UTF-8 CSV with a header row. Required columns: product_code, batch_no, on_hand, expiry_date (YYYY-MM-DD), unit_cost_paise. Optional (blank = 0): reserved, allocated, safety_stock, quarantined. Max 1 MB. */
        requestBody: {
            content: {
                "text/csv": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_batch_api_v1_inventory_batches__batch_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_batch_api_v1_inventory_batches__batch_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shortages_api_v1_shortages_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ShortageOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_shortage_api_v1_shortages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShortageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shortage_api_v1_shortages__shortage_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shortage_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_shortage_api_v1_shortages__shortage_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shortage_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReasonIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rerun_match_api_v1_shortages__shortage_id__match_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shortage_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReasonIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_match_run_api_v1_shortages__shortage_id__match_runs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shortage_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_telemetry_api_v1_internal_telemetry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetryBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelemetryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_devices_api_v1_devices_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DeviceOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_source_requests_api_v1_source_requests_get: {
        parameters: {
            query: {
                direction: components["schemas"]["Direction"];
                status?: components["schemas"]["RequestStatus"] | null;
                shortage_id?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SourceRequestOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_source_request_api_v1_source_requests__request_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReasonIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decline_source_request_api_v1_source_requests__request_id__decline_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReasonIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRequestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_stream_ticket_api_v1_events_ticket_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamTicketOut"];
                };
            };
        };
    };
    event_stream_api_v1_events_stream_get: {
        parameters: {
            query?: {
                last_event_id?: number | null;
                /** @description A stream ticket from POST /events/ticket. */
                ticket?: string | null;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_webhooks_api_v1_webhooks_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_WebhookOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_webhook_api_v1_webhooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_webhook_api_v1_webhooks__webhook_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                webhook_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReasonIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
