/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Org
         * @description Own org in full; any other org: name, type and location only.
         */
        get: operations["get_org_api_v1_orgs__org_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org_id}/facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Facilities
         * @description Own org's facilities in full; another org's: name and location only.
         */
        get: operations["list_facilities_api_v1_orgs__org_id__facilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit
         * @description Own org's rows, newest first; the platform admin sees every org's rows.
         */
        get: operations["list_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Products
         * @description The shared catalog; any signed-in user.
         */
        get: operations["list_products_api_v1_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_v1_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/supplier-offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Offers
         * @description The caller's own org's offers only.
         */
        get: operations["list_offers_api_v1_supplier_offers_get"];
        /**
         * Put Offer
         * @description Create or update one offer of the caller's supplier org (SUPPLIER orgs only).
         */
        put: operations["put_offer_api_v1_supplier_offers_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Batches
         * @description The caller's own org's batches, each with the hub-computed `transferable`.
         */
        get: operations["list_batches_api_v1_inventory_batches_get"];
        put?: never;
        /** Create Batch */
        post: operations["create_batch_api_v1_inventory_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/batches/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Batches
         * @description Insert each valid row into `facility_id`; report invalid rows by line number.
         */
        post: operations["import_batches_api_v1_inventory_batches_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Batch */
        patch: operations["update_batch_api_v1_inventory_batches__batch_id__patch"];
        trace?: never;
    };
    "/api/v1/inventory/batches/{batch_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Batch
         * @description Record a physical count: writes a VerificationEvent, sets last_verified_at, and a
         *     count that differs from on_hand replaces it.
         */
        post: operations["verify_batch_api_v1_inventory_batches__batch_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditOut */
        AuditOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Actor Id */
            actor_id: string | null;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Entity */
            entity: string;
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Action */
            action: string;
            /** Before */
            before: {
                [key: string]: unknown;
            } | null;
            /** After */
            after: {
                [key: string]: unknown;
            } | null;
            /** Reason */
            reason: string;
            /** Reason Source */
            reason_source: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /** BatchCreate */
        BatchCreate: {
            /** Batch No */
            batch_no: string;
            /** On Hand */
            on_hand: number;
            /**
             * Reserved
             * @default 0
             */
            reserved: number;
            /**
             * Allocated
             * @default 0
             */
            allocated: number;
            /**
             * Safety Stock
             * @default 0
             */
            safety_stock: number;
            /**
             * Quarantined
             * @default 0
             */
            quarantined: number;
            /**
             * Expiry Date
             * Format: date
             */
            expiry_date: string;
            /** Unit Cost Paise */
            unit_cost_paise: number;
            /**
             * Facility Id
             * Format: uuid
             */
            facility_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Reason */
            reason?: string | null;
        };
        /** BatchOut */
        BatchOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * Facility Id
             * Format: uuid
             */
            facility_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Batch No */
            batch_no: string;
            /** On Hand */
            on_hand: number;
            /** Reserved */
            reserved: number;
            /** Allocated */
            allocated: number;
            /** Safety Stock */
            safety_stock: number;
            /** Quarantined */
            quarantined: number;
            /**
             * Expiry Date
             * Format: date
             */
            expiry_date: string;
            /** Unit Cost Paise */
            unit_cost_paise: number;
            /** Last Verified At */
            last_verified_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Transferable
             * @description Hub-computed (business-rules.md §2); never accepted as input.
             */
            readonly transferable: number;
        };
        /**
         * BatchUpdate
         * @description Partial update. Product and facility are fixed; omitted or null fields are unchanged.
         */
        BatchUpdate: {
            /** Batch No */
            batch_no?: string | null;
            /** On Hand */
            on_hand?: number | null;
            /** Reserved */
            reserved?: number | null;
            /** Allocated */
            allocated?: number | null;
            /** Safety Stock */
            safety_stock?: number | null;
            /** Quarantined */
            quarantined?: number | null;
            /** Expiry Date */
            expiry_date?: string | null;
            /** Unit Cost Paise */
            unit_cost_paise?: number | null;
            /** Reason */
            reason?: string | null;
        };
        /** FacilityOut */
        FacilityOut: {
            /** Name */
            name: string;
            location: components["schemas"]["Location"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Address */
            address: string;
            /** Has Cold Storage */
            has_cold_storage: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportResult */
        ImportResult: {
            /** Inserted */
            inserted: number;
            /** Errors */
            errors: components["schemas"]["RowError"][];
        };
        /** Location */
        Location: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** MeOut */
        MeOut: {
            user: components["schemas"]["UserOut"];
            org: components["schemas"]["OrgOut"];
            /** Roles */
            roles: string[];
            /** Capabilities */
            capabilities: string[];
        };
        /**
         * OfferIn
         * @description One offer per PUT, keyed by the caller's org and `product_id` (upsert).
         */
        OfferIn: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Unit Price Paise */
            unit_price_paise: number;
            /** Lead Time Hours */
            lead_time_hours: number;
            /** Available Qty */
            available_qty: number;
            /** Reason */
            reason?: string | null;
        };
        /** OfferOut */
        OfferOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Unit Price Paise */
            unit_price_paise: number;
            /** Lead Time Hours */
            lead_time_hours: number;
            /** Available Qty */
            available_qty: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OrgOut */
        OrgOut: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            location: components["schemas"]["Location"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
        };
        /** Page[AuditOut] */
        Page_AuditOut_: {
            /** Items */
            items: components["schemas"]["AuditOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[BatchOut] */
        Page_BatchOut_: {
            /** Items */
            items: components["schemas"]["BatchOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[FacilityOut] */
        Page_FacilityOut_: {
            /** Items */
            items: components["schemas"]["FacilityOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[OfferOut] */
        Page_OfferOut_: {
            /** Items */
            items: components["schemas"]["OfferOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[ProductOut] */
        Page_ProductOut_: {
            /** Items */
            items: components["schemas"]["ProductOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** Page[PublicFacilityView] */
        Page_PublicFacilityView_: {
            /** Items */
            items: components["schemas"]["PublicFacilityView"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ProductOut */
        ProductOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Unit */
            unit: string;
            /** Requires Cold Chain */
            requires_cold_chain: boolean;
            /** Temp Min C */
            temp_min_c: number | null;
            /** Temp Max C */
            temp_max_c: number | null;
            /** Default Min Shelf Life Days */
            default_min_shelf_life_days: number;
        };
        /** PublicFacilityView */
        PublicFacilityView: {
            /** Name */
            name: string;
            location: components["schemas"]["Location"];
        };
        /**
         * PublicOrgView
         * @description What any org may see of another org: name, type, location only.
         */
        PublicOrgView: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            location: components["schemas"]["Location"];
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RowError */
        RowError: {
            /** Line */
            line: number;
            /** Message */
            message: string;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerificationMethod
         * @enum {string}
         */
        VerificationMethod: "MANUAL" | "SCAN";
        /**
         * VerifyIn
         * @description `method` is required: the hub records only the count method the user stated.
         */
        VerifyIn: {
            method: components["schemas"]["VerificationMethod"];
            /** Counted Qty */
            counted_qty: number;
            /** Reason */
            reason?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    get_org_api_v1_orgs__org_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgOut"] | components["schemas"]["PublicOrgView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_facilities_api_v1_orgs__org_id__facilities_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FacilityOut_"] | components["schemas"]["Page_PublicFacilityView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_v1_audit_get: {
        parameters: {
            query?: {
                entity?: string | null;
                entity_id?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_products_api_v1_products_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ProductOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_v1_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_offers_api_v1_supplier_offers_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OfferOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_offer_api_v1_supplier_offers_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_api_v1_inventory_batches_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BatchOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_batch_api_v1_inventory_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_batches_api_v1_inventory_batches_import_post: {
        parameters: {
            query: {
                facility_id: string;
                reason?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description UTF-8 CSV with a header row. Required columns: product_code, batch_no, on_hand, expiry_date (YYYY-MM-DD), unit_cost_paise. Optional (blank = 0): reserved, allocated, safety_stock, quarantined. Max 1 MB. */
        requestBody: {
            content: {
                "text/csv": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_batch_api_v1_inventory_batches__batch_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_batch_api_v1_inventory_batches__batch_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
